services:
  web:
    image: ghcr.io/alihassandev1/linkedops:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - backend
networks:
  backend: