name: Self Hosted Docker Test

on:
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: self-hosted

    steps:
      - name: Check Docker
        run: docker --version

      - name: Check Docker Compose
        run: docker compose version

      - name: Check Docker
        run: docker info
